config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users,only:[:new,:create,:show]
  resources :sessions,only:[:new,:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels,dependent: :destroy
  has_many :tasks,through: :task_labels,source: :task
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,presence: true,length:{maximum:50}
  validates :content,presence: true,length:{maximum:150}
  belongs_to :user
  has_many :task_labels,dependent: :destroy
  has_many :labels,through: :task_labels,source: :label

  def self.searchings(
       title = nil,
       status = nil
    )
    if title.present? && status.present?
      return Task.title_status_like_where(title,status)
    elsif title.empty? && status.present?
      return Task.status_like_where(status)
    elsif title.present? && status.empty?
      return Task.title_like_where(title)
    else
      return Task.created_at_desc
    end
  end

  def self.sortings(
    deadline_sort = false,
    priority_sort = false
    )
    if deadline_sort
      return Task.deadline_desc
    elsif priority_sort
      return Task.priority_asc
    else
      return Task.created_at_desc
    end
  end
  # def self.sortings(
  #      sort = false
  #   )
  #   if sort
  #     return Task.deadline_desc
  #   else
  #     return Task.created_at_desc
  #   end
  # end

  enum priority:{high:0,moderate:1,low:2}

  scope :created_at_desc, -> {all.order(created_at: :desc)}
  scope :deadline_desc, -> {all.order(deadline: :desc)}
  scope :priority_asc, -> {all.order(priority: :asc)}
  scope :title_status_like_where, -> (params1,params2){where("title LIKE ? AND status LIKE ?","%#{params1}%","%#{params2}%")}
  scope :title_like_where, -> (params){where("title LIKE ?","%#{params}%")}
  scope :status_like_where, -> (params){where("status LIKE ?","%#{params}%")}
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  before_validation{ email.downcase! }
  has_secure_password
  validates :name,presence:true,length:{maximum:30}
  validates :email,presence:true,length:{maximum:255},uniqueness: true
  has_many :tasks,dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy destroy_stop)
  before_action :authenticate_user
  before_action :user_ensure_admin_user
  before_action :admin_least_one,only: %i(update destroy)

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id),notice: "管理者権限でユーザー登録しました！"
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id),notice: "管理者権限でユーザー情報を編集しました！"
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    if @user.destroy
      redirect_to admin_users_path,notice:"管理者権限でユーザーを削除しました"
    end
  end

  def user_ensure_admin_user
    if current_user.admin == false
      raise Forbidden
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def admin_least_one
    if User.where(admin: "true").count == 1  && @user.admin == true
      redirect_to admin_users_path,notice:"管理者は最低１人必要です"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      redirect_to new_session_path,notice:"ログインが必要です"
    end
  end

  class Forbidden < ActionController::ActionControllerError
  end

  rescue_from Forbidden, with: :rescue403

  private
    def rescue403(e)
      @exception = e
      render template: "layouts/forbidden",status: 403
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logget_in?
      redirect_to user_path(current_user.id),notice: "既にログインしています"
    end
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id),notice: "ログインしました"
    else
      flash.now[:notice] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task,only: %i(show edit destroy update task_ensure_correct_user)
  before_action :task_ensure_correct_user,only: %i(show edit update destroy)
  before_action :authenticate_user
  def index
    label_id = Label.find_by(id:params[:label_search]).id if params[:label_search].present?
    task_ids = TaskLabel.where(label_id:label_id).pluck(:task_id).to_a
    @tasks =
    if params[:search] == "true"
      if params[:label_search].present?
        current_user.tasks.where(id:task_ids).page(params[:page]).per(12)
      else
        current_user.tasks.searchings(
          params[:title_search],
          params[:status_search]
          ).page(params[:page]).per(12)
      end
    else
      current_user.tasks.sortings(
        params[:sort_expired],
        params[:sort_priority]
        ).page(params[:page]).per(12)
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path,notice:"タスクを追加しました!"
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path,notice:"タスクを編集しました!"
    else
      render "edit"
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path,notice:"タスクを削除しました!"
  end

  def task_ensure_correct_user
    if @task.user_id != current_user.id
      redirect_to user_path(current_user.id),notice:"権限がありません"
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :deadline, :status, :priority,label_ids:[])
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: %i(show user_ensure_correct_user)
  before_action :authenticate_user,only: %i(show)
  before_action :user_ensure_correct_user,only: %i(show)
  def new
    if logget_in?
      redirect_to user_path(current_user.id),notice: "ログインしています"
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id),notice: "ユーザー登録完了しました！ログインしています"
    else
      render "new"
    end
  end

  def show
  end

  def user_ensure_correct_user
    if @user.id != current_user.id
      redirect_to user_path(current_user.id),notice: "権限がありません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logget_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= form_with(model: @user,local: true,url: admin_user_path) do |f| %>
  <% if @user.errors.any? %>
  <h2><%= @user.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.label :admin %>
    <label><%= f.radio_button :admin,"true" %>管理者</label>
    <label><%= f.radio_button :admin,"false" %>一般ユーザー</label>
  </div>

  <%= f.submit %>
<% end %>

app/views/admin/users/index.html.erb
<h1>ユーザー 一覧</h1>

<div class="table-responsive">
  <table class="table table-bordered table-sm table-hover">
    <tr class="table-info">
      <th class="text" width="50%">ユーザー名</th>
      <th class="text" width="20%">タスク保持数</th>
      <th class="text" width="30%"></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.tasks.count %></td>
        <td class="link">
          <%= link_to t("view.show"),admin_user_path(user.id),class:"btn btn-info btn-sm" %>
          <%= link_to t("view.edit"),edit_admin_user_path(user.id),class:"btn btn-warning btn-sm" %>
          <%= link_to t("view.delete"),admin_user_path(user.id),method: :delete,data:{confirm:t("view.Are you really sure?")},class:"btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to "新規ユーザー登録",new_admin_user_path %>
</div>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_with(model: @user,local: true,url: admin_users_path) do |f| %>
  <% if @user.errors.any? %>
  <h2><%= @user.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.label :admin %>
    <label><%= f.radio_button :admin,"true" %>管理者</label>
    <label><%= f.radio_button :admin,"false" %>一般ユーザー</label>
  </div>

  <%= f.submit %>
<% end %>
<%= link_to "ユーザー 一覧",admin_users_path %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>様のページ</h1>
<div>
  <% if @user.admin == true %>
    このユーザーは管理者です
  <% end %>
</div>
<div>メールアドレス:<%= @user.email %></div>
<%= link_to "このユーザーを削除する",admin_user_path(@user.id),method: :delete,data:{confirm:t("view.Are you really sure?")} %>
<h3><%= @user.name %>様のタスク一覧</h3>
<div class="table-responsive">
  <table class="table table-bordered table-sm table-hover">
    <tr class="table-info">
      <th class="text" width="40%">タイトル</th>
      <th class="text" width="20%">終了期限</th>
      <th class="text" width="20%">進捗状態</th>
      <th class="text" width="20%">優先順位</th>
    </tr>
    <% @user.tasks.each do |task| %>
    <tr>
      <td class="text"><%= task.title %></td>
      <td class="text"><%= task.deadline.strftime("%Y%m月%d日") %></td>
      <td class="text"><%= task.status %></td>
      <% if task.priority_i18n == "高" %>
        <td class="text priority high"><%= task.priority_i18n %></td>
      <% elsif task.priority_i18n == "中" %>
        <td class="text priority moderate"><%= task.priority_i18n %></td>
      <% elsif task.priority_i18n == "低"%>
        <td class="text priority low"><%= task.priority_i18n %></td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <span class="navbar-brand"><%= link_to "TaskManagement",tasks_path %></span>
    <div class="collapse navbar-collapse">
      <% if logget_in?%>
        <% if current_user.admin == false%>
          <span class="navbar-text ml-auto">
            <%= link_to current_user.name,user_path(current_user.id) %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.index"),tasks_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.new"),new_task_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.logout"),session_path(current_user.id),method: :delete %>
          </span>
        <% elsif current_user.admin == true %>
          <span class="navbar-text ml-auto">
            <%= link_to current_user.name,user_path(current_user.id) %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.index"),tasks_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.new"),new_task_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.user_index"),admin_users_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.user_new"),new_admin_user_path %>
          </span>
          <span class="navbar-text ml-auto">
            <%= link_to t("view.logout"),session_path(current_user.id),method: :delete %>
          </span>
        <% end %>
      <% else %>
      <span class="navbar-text ml-auto">
        <%= link_to t("view.user_new"),new_user_path %>
        <%= link_to t("view.login"),new_session_path %>
      </span>
      <% end %>
    </div>
  </nav>
  <% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/forbidden.html.erb
<div id="erros">
  <h1>403 Forbidden</h1>
  <p>指定されたページを表示する権限がありません</p>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model:@task,local:true) do |f| %>
  <% if @task.errors.any? %>
    <h2><%= @task.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="task_title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="task_content">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="task_deadline">
    <%= f.label :deadline %>
    <%= f.date_field :deadline %>
  </div>
  <div class="task_status">
    <%= f.label :status %>
    <%= f.select :status,["未着手","着手中","完了"] %>
  </div>
  <div class="task_priority">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities.keys.map{|k| [Task.priorities_i18n[k],k]} %>
  </div>
  <% Label.all.each do |label| %>
    <%= f.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %><%= label.category %>
  <% end %>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>
<%= render "form" %>
<%= link_to t("view.back"),tasks_path %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>
<div class="search-form">
  <%= form_with(method: :get,local: true) do |f| %>
  <%= f.label :title_search,"タイトル検索" %>
  <%= f.text_field :title_search %>
  <%= f.label :status_search,"状態検索"%>
  <%= f.select :status_search,["","未着手","着手中","完了"] %>
  <%= f.label :label_search,"ラベル検索" %>
  <%= f.select :label_search,[""] + Label.all.map{|l| [l.category,l.id]} %>
  <%= f.hidden_field :search,value: "true" %>
  <%= f.submit t("view.search") %>
  <% end %>
</div>
<br>
<div class="table-responsive">
  <table class="table table-bordered table-sm table-hover">
    <tr class="table-info">
      <th class="text" width="30%">タイトル</th>
      <th class="text" width="20%">終了期限</th>
      <th class="text" width="10%">進捗状態</th>
      <th class="text" width="10%">優先順位</th>
      <th class="text" width="10%">ラベル</th>
      <th width="20%"></th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td class="text"><%= task.title %></td>
      <td class="text"><%= task.deadline.strftime("%Y%m月%d日") %></td>
      <td class="text"><%= task.status %></td>
      <% if task.priority_i18n == "高" %>
        <td class="text priority high"><%= task.priority_i18n %></td>
      <% elsif task.priority_i18n == "中" %>
        <td class="text priority moderate"><%= task.priority_i18n %></td>
      <% elsif task.priority_i18n == "低"%>
        <td class="text priority low"><%= task.priority_i18n %></td>
      <% end %>
      <td class="text">
        <% task.labels.each do |label|  %>
         <span class="label"><%= label.category %></span>
        <% end %>
        </td>
      <td class="link">
        <%= link_to t("view.show"),task_path(task.id),class:"btn btn-info btn-sm" %>
        <%= link_to t("view.edit"),edit_task_path(task.id),class:"btn btn-warning btn-sm" %>
        <%= link_to t("view.delete"),task_path(task.id),method: :delete,data:{confirm:t("view.Are you really sure?")},class:"btn btn-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<div>
  <%= paginate @tasks %>
</div>
<br>
<div class="link">
  <%= link_to t("view.deadline_sort"),tasks_path(sort_expired: "true") %>
  <%= link_to t("view.priority_sort"),tasks_path(sort_priority: "true") %>
</div>
<br>
<div class="link">
  <%= link_to t("view.new"),new_task_path %>
</div>

app/views/tasks/new.html.erb
<h2>タスク新規登録</h2>
<%= render "form" %>
<%= link_to t("view.back"),tasks_path %>

app/views/tasks/show.html.erb
<h2>タスク詳細</h2>
<br>
<div class="table-responsive">
  <table class="table table-bordered table-sm table-hover">
    <tr>
      <td class="text">
        <%= @task.title %>
      </td>
    </tr>
    <tr>
      <td class="text">
        <%= @task.content %>
      </td>
    </tr>
    <tr>
      <td class="text">
        <%= @task.deadline.strftime("%Y年%m月%d日") %>
      </td>
    </tr>
    <tr>
      <td class="text">
        <%= @task.status %>
      </td>
    </tr>
    <tr>
      <% if @task.priority_i18n == "高" %>
        <td class="text priority high"><%= @task.priority_i18n %></td>
      <% elsif @task.priority_i18n == "中" %>
        <td class="text priority moderate"><%= @task.priority_i18n %></td>
      <% elsif @task.priority_i18n == "低"%>
        <td class="text priority low"><%= @task.priority_i18n %></td>
      <% end %>
    </tr>
    <tr>
      <td>
        <% @task.labels.each do |label| %>
          <%= label.category %>
        <% end %>
      </td>
    </tr>
  </table>
</div>
<%= link_to t("view.edit"),edit_task_path(@task.id) %>
<%= link_to t("view.delete"),task_path(@task.id),method: :delete,data:{confirm:t("Are you really sure?")} %>
<div><%= link_to t("view.back"),tasks_path %></div>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_with(model: @user,local: true) do |f| %>
  <% if @user.errors.any? %>
  <h2><%= @user.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のマイページ</h1>

<div>メールアドレス:<%= @user.email %></div>